name = "grounds-landing"
main = "src/worker.ts"
compatibility_date = "2025-10-09"
workers_dev = false

[[routes]]
pattern = "grounds.gg"
custom_domain = true

[[routes]]
pattern = "www.grounds.gg"
custom_domain = true

[assets]
directory = "public"

[observability]
enabled = true